- name: Status firewalld
  shell: >
    systemctl status firewalld | grep active || echo "not be found"
  register: firewalld_already_installed

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: '"active" in firewalld_already_installed.stdout'

# 安装基础组件
- name: Download base package | CentOS
  get_url:
    validate_certs: no
    url: "{{ base_rpm_download_url }}"
    dest: "{{ base_dir }}/packages"
    timeout: "{{ download_timeout_online }}"

- name: Unarchive base package | CentOS
  unarchive:
    src: "{{ base_dir }}/packages/{{ ansible_distribution }}_base_{{ ansible_architecture }}.tar.gz"
    dest: "{{ base_dir }}/chrony"
    remote_src: yes

- name: Install base package | CentOS
  shell: "rpm -Uvh {{ base_dir }}/packages/{{ ansible_distribution }}_base/*.rpm"

# 安装 ipvs
- name: Install ipvs rpm package
  package:
    name:
    - ipset
    - ipvsadm
    state: latest
  when: kube_proxy_mode == "ipvs"

- name: Temp stop selinux
  shell: "setenforce 0"
  failed_when: false

- name: Disable selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

# 优化设置 journal 日志相关，避免日志重复搜集，浪费系统资源
- name: Disable rsyslog Get journald log 1
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'ModLoad imjournal'
    line: '#$ModLoad imjournal # provides access to the systemd journal'

- name: Disable rsyslog Get journald log 2
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'IMJournalStateFile'
    line: '#$IMJournalStateFile imjournal.state'

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  ignore_errors: true