- name: Run "apt-get update"
  shell: "rm -rf /var/lib/apt/lists/* && /usr/bin/apt-get update -y"

- name: Install Python-apt （'Ubuntu Magjor Version' = 18）
  shell: "/usr/bin/apt-get install python-apt -y"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"

- name: Status firewalld
  shell: >
    systemctl status ufw | grep active || echo "not be found"
  register: ufw_already_installed

- name: Debian |Disable UFW
  service:
    name: ufw
    state: stopped
    enabled: no
  when: '"active" in ufw_already_installed.stdout'

# 安装基础组件
- name: Download base package | Debian
  get_url:
    validate_certs: no
    url: "{{ base_deb_download_url }}"
    dest: "{{ base_dir }}/packages"
    timeout: "{{ download_timeout_online }}"

- name: Unarchive base package | Debian
  unarchive:
    src: "{{ base_dir }}/packages/{{ ansible_distribution }}_{{ ansible_distribution_release }}_base_{{ ansible_architecture }}.tar.gz"
    dest: "{{ base_dir }}/packages"
    remote_src: yes

- name: Install base package | Debian
  shell: "dpkg -i {{ base_dir }}/packages/{{ ansible_distribution }}_{{ ansible_distribution_release }}_base/*.deb"

# 安装 ipvs
- name: Debian | Install ipvs  package
  package:
    name:
    - ipset
    - ipvsadm
    state: latest
  when: kube_proxy_mode == "ipvs"

- name: Disable rsyslog Get journald log 1
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'ModLoad imjournal'
    line: '#$ModLoad imjournal # provides access to the systemd journal'

- name: Disable rsyslog Get journald log 2
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'IMJournalStateFile'
    line: '#$IMJournalStateFile imjournal.state'

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  ignore_errors: true